services:
  postgres:
    image: postgres:16
    container_name: dockerdbmonedas
    ports: 
      - "5440:5432"
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sa
      POSTGRES_DB: monedas
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
    networks: 
      - red

networks:
  red:
    driver: bridge