# Utilizar la imagen oficial de PostgreSQL desde Docker Hub
FROM postgres:latest

# Copia los scripts de DDL y DML al directorio de Docker
COPY DDL_Monedas.sql /docker-entrypoint-initdb.d/
COPY DML_Monedas.sql /docker-entrypoint-initdb.d/
